services:
  - type: web
    name: listify
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: EXPO_PUBLIC_SUPABASE_URL
        sync: false
      - key: EXPO_PUBLIC_SUPABASE_ANON_KEY
        sync: false
