/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Button`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Input`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Card`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/use-color-scheme`; params?: Router.UnknownInputParams; } | { pathname: `/../types/shopping`; params?: Router.UnknownInputParams; } | { pathname: `/../redux/shoppingListReducer`; params?: Router.UnknownInputParams; } | { pathname: `/../redux/shoppingListActions`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ShoppingItem`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/AddItemForm`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore_new` | `/explore_new`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/Button`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/Input`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/Card`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/use-color-scheme`; params?: Router.UnknownOutputParams; } | { pathname: `/../types/shopping`; params?: Router.UnknownOutputParams; } | { pathname: `/../redux/shoppingListReducer`; params?: Router.UnknownOutputParams; } | { pathname: `/../redux/shoppingListActions`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ShoppingItem`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/AddItemForm`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore_new` | `/explore_new`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/../components/ui/Button${`?${string}` | `#${string}` | ''}` | `/../components/ui/Input${`?${string}` | `#${string}` | ''}` | `/../components/ui/Card${`?${string}` | `#${string}` | ''}` | `/../hooks/use-color-scheme${`?${string}` | `#${string}` | ''}` | `/../types/shopping${`?${string}` | `#${string}` | ''}` | `/../redux/shoppingListReducer${`?${string}` | `#${string}` | ''}` | `/../redux/shoppingListActions${`?${string}` | `#${string}` | ''}` | `/../components/ShoppingItem${`?${string}` | `#${string}` | ''}` | `/../components/ui/index${`?${string}` | `#${string}` | ''}` | `/../components/AddItemForm${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore_new${`?${string}` | `#${string}` | ''}` | `/explore_new${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Button`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Input`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/Card`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/use-color-scheme`; params?: Router.UnknownInputParams; } | { pathname: `/../types/shopping`; params?: Router.UnknownInputParams; } | { pathname: `/../redux/shoppingListReducer`; params?: Router.UnknownInputParams; } | { pathname: `/../redux/shoppingListActions`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ShoppingItem`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/AddItemForm`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore_new` | `/explore_new`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
