/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/../supabase/localStorageService`; params?: Router.UnknownInputParams; } | { pathname: `/../supabase/unifiedShoppingService`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Confetti`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/use-responsive`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/AppSettingsContext`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ConfirmationModal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore_new` | `/explore_new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/../supabase/localStorageService`; params?: Router.UnknownOutputParams; } | { pathname: `/../supabase/unifiedShoppingService`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Confetti`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/use-responsive`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/../contexts/AppSettingsContext`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ConfirmationModal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore_new` | `/explore_new`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/../supabase/localStorageService${`?${string}` | `#${string}` | ''}` | `/../supabase/unifiedShoppingService${`?${string}` | `#${string}` | ''}` | `/../components/Confetti${`?${string}` | `#${string}` | ''}` | `/../hooks/use-responsive${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/../contexts/AppSettingsContext${`?${string}` | `#${string}` | ''}` | `/../components/ConfirmationModal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore_new${`?${string}` | `#${string}` | ''}` | `/explore_new${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/../supabase/localStorageService`; params?: Router.UnknownInputParams; } | { pathname: `/../supabase/unifiedShoppingService`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Confetti`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/use-responsive`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/AppSettingsContext`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ConfirmationModal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore_new` | `/explore_new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
